//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVCAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueBook
    {
        public int IssueBookID { get; set; }
        public int UserID { get; set; }
        public int EmployeeID { get; set; }
        public int IssueCopies { get; set; }
        public System.DateTime IssuesDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
        public bool ReservedNoOfcopies { get; set; }
        public Nullable<int> BookID { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual User User { get; set; }
        public virtual Book Book { get; set; }
    }
}
