//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMVCAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTable
    {
        public int PurchaseID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PurchaseAmount { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> BookID { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual Book Book { get; set; }
    }
}
